# Generated by Django 5.1.2 on 2024-10-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_pergunta_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='resposta',
            field=models.TextField(blank=True, help_text='Resposta para a pergunta', null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(help_text='Texto da pergunta', max_length=1000),
        ),
    ]
